//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.29 at 01:22:18 PM EEST 
//


package dk.frv.eavdam.io.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A class for holding all information for AIS base station coverage area.
 * 
 * <p>Java class for aisFixedStationCoverage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="aisFixedStationCoverage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="point" type="{http://eavdam.frv.dk/schema}coveragePoint"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aisFixedStationCoverage", propOrder = {
    "point"
})
public class AisFixedStationCoverage {

    @XmlElement(required = true)
    protected CoveragePoint point;

    /**
     * Gets the value of the point property.
     * 
     * @return
     *     possible object is
     *     {@link CoveragePoint }
     *     
     */
    public CoveragePoint getPoint() {
        return point;
    }

    /**
     * Sets the value of the point property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoveragePoint }
     *     
     */
    public void setPoint(CoveragePoint value) {
        this.point = value;
    }

}
