//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.07 at 03:43:47 PM EEST 
//


package dk.frv.eavdam.io.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3c.dom.Element;


/**
 * A class for holding all properties of an AIS base station.
 * 
 * <p>Java class for aisFixedStationData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="aisFixedStationData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stationName" type="{http://eavdam.frv.dk/schema}nonEmptyString"/>
 *         &lt;element name="lat" type="{http://eavdam.frv.dk/schema}lat"/>
 *         &lt;element name="lon" type="{http://eavdam.frv.dk/schema}lon"/>
 *         &lt;element name="mmsi" type="{http://eavdam.frv.dk/schema}mmsiNumber"/>
 *         &lt;element name="transmissionPower" type="{http://eavdam.frv.dk/schema}nonNegativeDouble"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="coverage" type="{http://eavdam.frv.dk/schema}aisFixedStationCoverage" maxOccurs="unbounded"/>
 *         &lt;element name="antenna" type="{http://eavdam.frv.dk/schema}antenna"/>
 *         &lt;element name="fatdmaAllocation" type="{http://eavdam.frv.dk/schema}fatdmaSlotAllocation"/>
 *         &lt;element name="stationType" type="{http://eavdam.frv.dk/schema}aisFixedStationType"/>
 *         &lt;sequence>
 *           &lt;element name="status" type="{http://eavdam.frv.dk/schema}aisFixedStationStatus"/>
 *           &lt;element name="startDate" type="{http://eavdam.frv.dk/schema}startDate"/>
 *           &lt;element name="endDate" type="{http://eavdam.frv.dk/schema}endDate"/>
 *         &lt;/sequence>
 *         &lt;any processContents='skip' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aisFixedStationData", propOrder = {
    "stationName",
    "lat",
    "lon",
    "mmsi",
    "transmissionPower",
    "description",
    "coverage",
    "antenna",
    "fatdmaAllocation",
    "stationType",
    "status",
    "startDate",
    "endDate",
    "any"
})
public class AisFixedStationData {

    @XmlElement(required = true)
    protected String stationName;
    protected double lat;
    protected double lon;
    @XmlElement(required = true, nillable = true)
    protected String mmsi;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double transmissionPower;
    @XmlElement(required = true, nillable = true)
    protected String description;
    @XmlElement(required = true, nillable = true)
    protected List<AisFixedStationCoverage> coverage;
    @XmlElement(required = true, nillable = true)
    protected Antenna antenna;
    @XmlElement(required = true, nillable = true)
    protected FatdmaSlotAllocation fatdmaAllocation;
    @XmlElement(required = true)
    protected AisFixedStationType stationType;
    @XmlElement(required = true)
    protected AisFixedStationStatus status;
    @XmlElement(required = true)
    protected XMLGregorianCalendar startDate;
    @XmlElement(required = true)
    protected XMLGregorianCalendar endDate;
    @XmlAnyElement
    protected List<Element> any;

    /**
     * Gets the value of the stationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * Sets the value of the stationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationName(String value) {
        this.stationName = value;
    }

    /**
     * Gets the value of the lat property.
     * 
     */
    public double getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     * 
     */
    public void setLat(double value) {
        this.lat = value;
    }

    /**
     * Gets the value of the lon property.
     * 
     */
    public double getLon() {
        return lon;
    }

    /**
     * Sets the value of the lon property.
     * 
     */
    public void setLon(double value) {
        this.lon = value;
    }

    /**
     * Gets the value of the mmsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMmsi() {
        return mmsi;
    }

    /**
     * Sets the value of the mmsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMmsi(String value) {
        this.mmsi = value;
    }

    /**
     * Gets the value of the transmissionPower property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTransmissionPower() {
        return transmissionPower;
    }

    /**
     * Sets the value of the transmissionPower property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTransmissionPower(Double value) {
        this.transmissionPower = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coverage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoverage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AisFixedStationCoverage }
     * 
     * 
     */
    public List<AisFixedStationCoverage> getCoverage() {
        if (coverage == null) {
            coverage = new ArrayList<AisFixedStationCoverage>();
        }
        return this.coverage;
    }

    /**
     * Gets the value of the antenna property.
     * 
     * @return
     *     possible object is
     *     {@link Antenna }
     *     
     */
    public Antenna getAntenna() {
        return antenna;
    }

    /**
     * Sets the value of the antenna property.
     * 
     * @param value
     *     allowed object is
     *     {@link Antenna }
     *     
     */
    public void setAntenna(Antenna value) {
        this.antenna = value;
    }

    /**
     * Gets the value of the fatdmaAllocation property.
     * 
     * @return
     *     possible object is
     *     {@link FatdmaSlotAllocation }
     *     
     */
    public FatdmaSlotAllocation getFatdmaAllocation() {
        return fatdmaAllocation;
    }

    /**
     * Sets the value of the fatdmaAllocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FatdmaSlotAllocation }
     *     
     */
    public void setFatdmaAllocation(FatdmaSlotAllocation value) {
        this.fatdmaAllocation = value;
    }

    /**
     * Gets the value of the stationType property.
     * 
     * @return
     *     possible object is
     *     {@link AisFixedStationType }
     *     
     */
    public AisFixedStationType getStationType() {
        return stationType;
    }

    /**
     * Sets the value of the stationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AisFixedStationType }
     *     
     */
    public void setStationType(AisFixedStationType value) {
        this.stationType = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link AisFixedStationStatus }
     *     
     */
    public AisFixedStationStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link AisFixedStationStatus }
     *     
     */
    public void setStatus(AisFixedStationStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * 
     * 
     */
    public List<Element> getAny() {
        if (any == null) {
            any = new ArrayList<Element>();
        }
        return this.any;
    }

}
