//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.07 at 01:04:38 PM EET 
//


package dk.frv.eavdam.io.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A class for holding all information for AIS base station coverage area.
 * 
 * <p>Java class for aisFixedStationCoverage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="aisFixedStationCoverage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="coverageType" type="{http://eavdam.frv.dk/schema}aisFixedStationCoverageType"/>
 *         &lt;sequence>
 *           &lt;element name="point" type="{http://eavdam.frv.dk/schema}coveragePoint" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aisFixedStationCoverage", propOrder = {
    "coverageType",
    "point"
})
public class AisFixedStationCoverage {

    @XmlElement(required = true)
    protected AisFixedStationCoverageType coverageType;
    protected List<CoveragePoint> point;

    /**
     * Gets the value of the coverageType property.
     * 
     * @return
     *     possible object is
     *     {@link AisFixedStationCoverageType }
     *     
     */
    public AisFixedStationCoverageType getCoverageType() {
        return coverageType;
    }

    /**
     * Sets the value of the coverageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AisFixedStationCoverageType }
     *     
     */
    public void setCoverageType(AisFixedStationCoverageType value) {
        this.coverageType = value;
    }

    /**
     * Gets the value of the point property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the point property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoveragePoint }
     * 
     * 
     */
    public List<CoveragePoint> getPoint() {
        if (point == null) {
            point = new ArrayList<CoveragePoint>();
        }
        return this.point;
    }

}
