//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.30 at 01:28:55 ip. EEST 
//


package dk.frv.eavdam.io.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for aisFixedStationStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="aisFixedStationStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="OPERATIVE"/>
 *     &lt;enumeration value="INOPERATIVE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "aisFixedStationStatus")
@XmlEnum
public enum AisFixedStationStatus {


    /**
     * Indicator that the station is in operative use.
     * 
     */
    OPERATIVE,

    /**
     * Indicator that the station is not in operative use, e.g. exists only on paper for scenario testing.
     * 
     */
    INOPERATIVE;

    public String value() {
        return name();
    }

    public static AisFixedStationStatus fromValue(String v) {
        return valueOf(v);
    }

}
