//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 09:13:36 AM EET 
//


package dk.frv.eavdam.io.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for aisFixedStationCoverageType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="aisFixedStationCoverageType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TRANSMISSION"/>
 *     &lt;enumeration value="RECEIVE"/>
 *     &lt;enumeration value="INTERFERENCE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "aisFixedStationCoverageType")
@XmlEnum
public enum AisFixedStationCoverageType {


    /**
     * Indicator of the transimission coverage area type.
     * 
     */
    TRANSMISSION,

    /**
     * Indicator of the receive coverage area type.
     * 
     */
    RECEIVE,

    /**
     * Indicator of the interference coverage area type.
     * 
     */
    INTERFERENCE;

    public String value() {
        return name();
    }

    public static AisFixedStationCoverageType fromValue(String v) {
        return valueOf(v);
    }

}
