//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 09:13:36 AM EET 
//


package dk.frv.eavdam.io.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for aisFixedStationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="aisFixedStationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BASESTATION"/>
 *     &lt;enumeration value="REPEATER"/>
 *     &lt;enumeration value="RECEIVER"/>
 *     &lt;enumeration value="ATON"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "aisFixedStationType")
@XmlEnum
public enum AisFixedStationType {

    BASESTATION,
    REPEATER,
    RECEIVER,
    ATON;

    public String value() {
        return name();
    }

    public static AisFixedStationType fromValue(String v) {
        return valueOf(v);
    }

}
