//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.07 at 01:04:38 PM EET 
//


package dk.frv.eavdam.io.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fatdmaSlotAllocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fatdmaSlotAllocation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fatdmaChannelA" type="{http://eavdam.frv.dk/schema}fatdmaChannel" minOccurs="0"/>
 *         &lt;element name="fatdmaChannelB" type="{http://eavdam.frv.dk/schema}fatdmaChannel" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fatdmaSlotAllocation", propOrder = {
    "fatdmaChannelA",
    "fatdmaChannelB"
})
public class FatdmaSlotAllocation {

    protected FatdmaChannel fatdmaChannelA;
    protected FatdmaChannel fatdmaChannelB;

    /**
     * Gets the value of the fatdmaChannelA property.
     * 
     * @return
     *     possible object is
     *     {@link FatdmaChannel }
     *     
     */
    public FatdmaChannel getFatdmaChannelA() {
        return fatdmaChannelA;
    }

    /**
     * Sets the value of the fatdmaChannelA property.
     * 
     * @param value
     *     allowed object is
     *     {@link FatdmaChannel }
     *     
     */
    public void setFatdmaChannelA(FatdmaChannel value) {
        this.fatdmaChannelA = value;
    }

    /**
     * Gets the value of the fatdmaChannelB property.
     * 
     * @return
     *     possible object is
     *     {@link FatdmaChannel }
     *     
     */
    public FatdmaChannel getFatdmaChannelB() {
        return fatdmaChannelB;
    }

    /**
     * Sets the value of the fatdmaChannelB property.
     * 
     * @param value
     *     allowed object is
     *     {@link FatdmaChannel }
     *     
     */
    public void setFatdmaChannelB(FatdmaChannel value) {
        this.fatdmaChannelB = value;
    }

}
