//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.07 at 01:04:38 PM EET 
//


package dk.frv.eavdam.io.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dk.frv.eavdam.io.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EavdamData_QNAME = new QName("http://eavdam.frv.dk/schema", "eavdamData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dk.frv.eavdam.io.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EavdamData }
     * 
     */
    public EavdamData createEavdamData() {
        return new EavdamData();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link FatdmaChannel }
     * 
     */
    public FatdmaChannel createFatdmaChannel() {
        return new FatdmaChannel();
    }

    /**
     * Create an instance of {@link ChannelBroadcast }
     * 
     */
    public ChannelBroadcast createChannelBroadcast() {
        return new ChannelBroadcast();
    }

    /**
     * Create an instance of {@link OmnidirectionalAntenna }
     * 
     */
    public OmnidirectionalAntenna createOmnidirectionalAntenna() {
        return new OmnidirectionalAntenna();
    }

    /**
     * Create an instance of {@link AisFixedStationCoverage }
     * 
     */
    public AisFixedStationCoverage createAisFixedStationCoverage() {
        return new AisFixedStationCoverage();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link CoveragePoint }
     * 
     */
    public CoveragePoint createCoveragePoint() {
        return new CoveragePoint();
    }

    /**
     * Create an instance of {@link Antenna }
     * 
     */
    public Antenna createAntenna() {
        return new Antenna();
    }

    /**
     * Create an instance of {@link FatdmaSlotAllocation }
     * 
     */
    public FatdmaSlotAllocation createFatdmaSlotAllocation() {
        return new FatdmaSlotAllocation();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AisFixedStationData }
     * 
     */
    public AisFixedStationData createAisFixedStationData() {
        return new AisFixedStationData();
    }

    /**
     * Create an instance of {@link DirectionalAntenna }
     * 
     */
    public DirectionalAntenna createDirectionalAntenna() {
        return new DirectionalAntenna();
    }

    /**
     * Create an instance of {@link EavdamUser }
     * 
     */
    public EavdamUser createEavdamUser() {
        return new EavdamUser();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EavdamData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://eavdam.frv.dk/schema", name = "eavdamData")
    public JAXBElement<EavdamData> createEavdamData(EavdamData value) {
        return new JAXBElement<EavdamData>(_EavdamData_QNAME, EavdamData.class, null, value);
    }

}
