//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.03 at 10:42:54 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://eavdam.frv.dk/schema")
package dk.frv.eavdam.io.jaxb;
